from __future__ import annotations

import subprocess
import sys
from pathlib import Path
from typing import Any

import httpx
import respx

from basin.codegen import openapi_to_types
from basin.codegen.emit import find_table_names


def _doc(paths: dict[str, Any]) -> dict[str, Any]:
    return {
        "openapi": "3.0.3",
        "info": {"title": "Basin REST API", "version": "0.1.0"},
        "paths": paths,
    }


def _table_path(name: str, props: dict[str, Any], required: list[str]) -> dict[str, Any]:
    return {
        f"/rest/v1/{name}": {
            "get": {
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {
                                        "type": "object",
                                        "required": required,
                                        "properties": props,
                                    },
                                }
                            }
                        },
                    }
                }
            }
        }
    }


USERS = _doc(
    _table_path(
        "users",
        {
            "id": {"type": "integer"},
            "email": {"type": "string"},
            "bio": {"type": "string", "nullable": True},
            "created_at": {"type": "string", "format": "date-time", "default": "now()"},
        },
        ["id", "email", "created_at"],
    )
)


def test_header_present() -> None:
    out = openapi_to_types(_doc({}))
    assert out.startswith("# This file is auto-generated by basin-sdk. Do not edit.")


def test_emits_typeddict_trio() -> None:
    out = openapi_to_types(USERS)
    assert "class UsersRow(TypedDict):" in out
    assert "class UsersInsert(TypedDict):" in out
    assert "class UsersUpdate(TypedDict):" in out


def test_type_mapping() -> None:
    out = openapi_to_types(USERS)
    row = out[out.index("class UsersRow") : out.index("class UsersInsert")]
    assert "id: int" in row
    assert "email: str" in row
    assert "bio: str | None" in row
    assert "created_at: str" in row


def test_insert_optionality() -> None:
    out = openapi_to_types(USERS)
    insert = out[out.index("class UsersInsert") : out.index("class UsersUpdate")]
    assert "id: int" in insert
    assert "email: str" in insert
    assert "bio: NotRequired[str | None]" in insert
    assert "created_at: NotRequired[str]" in insert


def test_update_all_optional() -> None:
    out = openapi_to_types(USERS)
    update = out[out.index("class UsersUpdate") :]
    assert "id: NotRequired[int]" in update
    assert "email: NotRequired[str]" in update


def test_database_aggregate() -> None:
    out = openapi_to_types(USERS)
    assert "Database = TypedDict(" in out
    assert '"users": UsersRow,' in out


def test_rpc_paths_ignored() -> None:
    doc = _doc(
        {
            **_table_path("users", {"id": {"type": "integer"}}, ["id"]),
            "/rest/v1/users/rpc/my_func": {
                "get": {"responses": {"200": {"description": "OK"}}}
            },
        }
    )
    out = openapi_to_types(doc)
    assert "UsersRow" in out
    assert "my_func" not in out


def test_multiple_tables() -> None:
    doc = _doc(
        {
            **_table_path("users", {"id": {"type": "integer"}}, ["id"]),
            **_table_path("products", {"sku": {"type": "string"}}, ["sku"]),
        }
    )
    out = openapi_to_types(doc)
    assert "class UsersRow(TypedDict):" in out
    assert "class ProductsRow(TypedDict):" in out


def test_array_and_object_types() -> None:
    doc = _doc(
        _table_path(
            "events",
            {
                "id": {"type": "integer"},
                "tags": {"type": "array", "items": {"type": "string"}},
                "payload": {"type": "object"},
            },
            ["id"],
        )
    )
    out = openapi_to_types(doc)
    assert "tags: list[str]" in out
    assert "payload: dict[str, Any]" in out


def test_falls_back_to_components_schemas() -> None:
    doc = {
        "openapi": "3.0.3",
        "info": {"title": "x", "version": "1"},
        "paths": {},
        "components": {
            "schemas": {
                "Account": {
                    "type": "object",
                    "required": ["id"],
                    "properties": {"id": {"type": "integer"}},
                }
            }
        },
    }
    out = openapi_to_types(doc)
    assert "class AccountRow(TypedDict):" in out


def test_non_identifier_column_uses_functional_typeddict() -> None:
    doc = _doc(
        _table_path(
            "weird",
            {"id": {"type": "integer"}, "first name": {"type": "string"}},
            ["id"],
        )
    )
    out = openapi_to_types(doc)
    assert 'WeirdRow = TypedDict(' in out
    assert '"first name": str' in out


def test_pydantic_variant() -> None:
    out = openapi_to_types(USERS, pydantic=True)
    assert "from pydantic import BaseModel" in out
    assert "from datetime import datetime" in out
    assert "class UsersRow(BaseModel):" in out
    assert "created_at: datetime" in out
    insert = out[out.index("class UsersInsert") : out.index("class UsersUpdate")]
    assert "bio: str | None = None" in insert


def test_find_table_names() -> None:
    doc = _doc(
        {
            **_table_path("users", {"id": {"type": "integer"}}, ["id"]),
            **_table_path("products", {"sku": {"type": "string"}}, ["sku"]),
        }
    )
    assert sorted(find_table_names(doc)) == ["products", "users"]


def test_generated_typeddict_module_compiles_and_typechecks(tmp_path: Path) -> None:
    out = openapi_to_types(USERS)
    module = tmp_path / "database.py"
    module.write_text(out)

    # compiles
    compile(out, str(module), "exec")

    # type-checks under mypy --strict
    result = subprocess.run(
        [sys.executable, "-m", "mypy", "--strict", str(module)],
        capture_output=True,
        text=True,
    )
    assert result.returncode == 0, result.stdout + result.stderr


def test_cli_writes_file(tmp_path: Path, capsys: Any) -> None:
    from basin.codegen.__main__ import main

    base = "http://localhost:5434"
    out_file = tmp_path / "database.py"
    with respx.mock:
        respx.get(f"{base}/rest/v1/_openapi.json").mock(
            return_value=httpx.Response(200, json=USERS)
        )
        main(["--url", base, "--key", "k", "--out", str(out_file)])

    assert out_file.exists()
    written = out_file.read_text()
    assert "class UsersRow(TypedDict):" in written
    captured = capsys.readouterr()
    assert "1 tables" in captured.out


def test_cli_pydantic_flag(tmp_path: Path) -> None:
    from basin.codegen.__main__ import main

    base = "http://localhost:5434"
    out_file = tmp_path / "models.py"
    with respx.mock:
        respx.get(f"{base}/rest/v1/_openapi.json").mock(
            return_value=httpx.Response(200, json=USERS)
        )
        main(["--url", base, "--key", "k", "--out", str(out_file), "--pydantic"])

    assert "from pydantic import BaseModel" in out_file.read_text()


def test_cli_fetch_failure_exits(tmp_path: Path) -> None:
    import pytest

    from basin.codegen.__main__ import main

    base = "http://localhost:5434"
    out_file = tmp_path / "database.py"
    with respx.mock:
        respx.get(f"{base}/rest/v1/_openapi.json").mock(
            return_value=httpx.Response(404, text="nope")
        )
        with pytest.raises(SystemExit):
            main(["--url", base, "--key", "k", "--out", str(out_file)])
