"""
OpenAPI → typed Python models — T-015.

``openapi_to_types(doc, *, pydantic=False)`` walks an OpenAPI document and
emits a single Python module: one ``TypedDict`` trio per table
(``{Table}Row`` / ``{Table}Insert`` / ``{Table}Update``), plus a ``Database``
aggregate ``TypedDict``.  With ``pydantic=True`` it emits pydantic v2
``BaseModel`` classes instead.

Mirrors basin-js ``openAPIDocToTypes`` (``src/codegen/openapi-to-types.ts``):
tables are discovered from ``/rest/v1/{table}`` GET responses, falling back to
``components.schemas`` when no table paths are present.  Insert makes
default/nullable/non-required columns optional; Update makes every column
optional.
"""

from __future__ import annotations

import keyword
import re
import subprocess
import sys
from dataclasses import dataclass

from ..openapi.types import OpenAPIDocument, OpenAPIPathItem, OpenAPISchema

_HEADER = "# This file is auto-generated by basin-sdk. Do not edit.\n"
_TABLE_PATH = re.compile(r"^/rest/v1/([^/]+)$")


def _map_primitive(schema: OpenAPISchema, *, pydantic: bool) -> str:
    t = schema.get("type")
    if t in ("integer",):
        return "int"
    if t == "number":
        return "float"
    if t == "boolean":
        return "bool"
    if t == "string":
        if pydantic and schema.get("format") in ("date-time", "date"):
            return "datetime"
        return "str"
    if t == "array":
        items = schema.get("items")
        inner = _map_type(items, pydantic=pydantic) if items else "Any"
        return f"list[{inner}]"
    if t == "object":
        return "dict[str, Any]"
    return "Any"


def _map_type(schema: OpenAPISchema, *, pydantic: bool) -> str:
    base = _map_primitive(schema, pydantic=pydantic)
    if schema.get("nullable") is True:
        return f"{base} | None"
    return base


@dataclass
class _Field:
    name: str
    py_type: str
    required: bool
    has_default: bool
    nullable: bool


@dataclass
class _Table:
    name: str
    fields: list[_Field]


def _extract_fields(schema: OpenAPISchema, *, pydantic: bool) -> list[_Field]:
    props = schema.get("properties")
    if not props:
        return []
    required = set(schema.get("required") or [])
    fields: list[_Field] = []
    for name, prop in props.items():
        fields.append(
            _Field(
                name=name,
                py_type=_map_type(prop, pydantic=pydantic),
                required=name in required,
                has_default="default" in prop,
                nullable=prop.get("nullable") is True,
            )
        )
    return fields


def _row_schema(item: OpenAPIPathItem) -> OpenAPISchema | None:
    get_op = item.get("get")
    if not get_op:
        return None
    responses = get_op.get("responses") or {}
    ok = responses.get("200") or {}
    content = ok.get("content") or {}
    media = content.get("application/json") or {}
    schema = media.get("schema")
    if not schema:
        return None
    items = schema.get("items")
    return items if items else schema


def find_table_names(doc: OpenAPIDocument) -> list[str]:
    """Return the names of every table the codegen would emit for ``doc``."""
    return [t.name for t in _find_tables(doc, pydantic=False)]


def _find_tables(doc: OpenAPIDocument, *, pydantic: bool) -> list[_Table]:
    tables: list[_Table] = []
    seen: set[str] = set()

    for path, item in (doc.get("paths") or {}).items():
        match = _TABLE_PATH.match(path)
        if not match:
            continue
        name = match.group(1)
        if not name or name in seen:
            continue
        seen.add(name)
        schema = _row_schema(item)
        fields = _extract_fields(schema, pydantic=pydantic) if schema else []
        tables.append(_Table(name=name, fields=fields))

    if not tables:
        components = doc.get("components") or {}
        schemas = components.get("schemas") or {}
        for name, schema in schemas.items():
            if name in seen:
                continue
            seen.add(name)
            tables.append(
                _Table(name=name, fields=_extract_fields(schema, pydantic=pydantic))
            )

    return tables


def _class_name(table: str, suffix: str) -> str:
    parts = re.split(r"[^0-9a-zA-Z]+", table)
    pascal = "".join(p[:1].upper() + p[1:] for p in parts if p)
    if not pascal or not pascal[0].isalpha():
        pascal = "Table" + pascal
    return pascal + suffix


def _field_key(name: str) -> tuple[str, bool]:
    """Return (key, is_safe_identifier) for a column name."""
    if name.isidentifier() and not keyword.iskeyword(name):
        return name, True
    return name, False


def _render_typeddict(class_name: str, fields: list[_Field], mode: str) -> str:
    """mode ∈ {row, insert, update}."""
    all_safe = all(_field_key(f.name)[1] for f in fields)
    if not all_safe:
        return _render_typeddict_functional(class_name, fields, mode)

    lines = [f"class {class_name}(TypedDict):"]
    if not fields:
        lines.append("    pass")
        return "\n".join(lines)
    for f in fields:
        optional = mode == "update" or (
            mode == "insert" and (f.has_default or f.nullable or not f.required)
        )
        anno = f"NotRequired[{f.py_type}]" if optional else f.py_type
        lines.append(f"    {f.name}: {anno}")
    return "\n".join(lines)


def _render_typeddict_functional(class_name: str, fields: list[_Field], mode: str) -> str:
    entries = []
    for f in fields:
        optional = mode == "update" or (
            mode == "insert" and (f.has_default or f.nullable or not f.required)
        )
        anno = f"NotRequired[{f.py_type}]" if optional else f.py_type
        entries.append(f'        {f.name!r}: {anno},')
    body = "\n".join(entries)
    return f'{class_name} = TypedDict(\n    "{class_name}",\n    {{\n{body}\n    }},\n)'


def _render_model(class_name: str, fields: list[_Field], mode: str) -> str:
    lines = [f"class {class_name}(BaseModel):"]
    if not fields:
        lines.append("    pass")
        return "\n".join(lines)
    for f in fields:
        optional = mode == "update" or (
            mode == "insert" and (f.has_default or f.nullable or not f.required)
        )
        if optional:
            anno = f.py_type if "None" in f.py_type else f"{f.py_type} | None"
            lines.append(f"    {f.name}: {anno} = None")
        else:
            lines.append(f"    {f.name}: {f.py_type}")
    return "\n".join(lines)


def openapi_to_types(doc: OpenAPIDocument, *, pydantic: bool = False) -> str:
    """Emit a Python module of typed row models for every table in ``doc``."""
    tables = _find_tables(doc, pydantic=pydantic)

    blocks: list[str] = [_HEADER]

    if pydantic:
        blocks.append("from __future__ import annotations\n")
        imports = ["from typing import Any"]
        if _uses_datetime(tables):
            imports.append("from datetime import datetime")
        imports.append("from pydantic import BaseModel")
        blocks.append("\n".join(imports) + "\n")
        render = _render_model
    else:
        blocks.append("from __future__ import annotations\n")
        imports = [
            "import sys",
            "from typing import Any, TypedDict",
            "",
            "if sys.version_info >= (3, 11):",
            "    from typing import NotRequired",
            "else:",
            "    from typing_extensions import NotRequired",
        ]
        blocks.append("\n".join(imports) + "\n")
        render = _render_typeddict

    db_entries: list[str] = []
    for table in tables:
        row = _class_name(table.name, "Row")
        insert = _class_name(table.name, "Insert")
        update = _class_name(table.name, "Update")
        blocks.append(render(row, table.fields, "row"))
        blocks.append(render(insert, table.fields, "insert"))
        blocks.append(render(update, table.fields, "update"))
        db_entries.append(f'        {table.name!r}: {row},')

    if pydantic:
        db_lines = [
            "class Database(BaseModel):",
            "    tables: dict[str, Any]",
        ]
        blocks.append("\n".join(db_lines))
    else:
        if db_entries:
            inner = "\n".join(db_entries)
            blocks.append(
                "Database = TypedDict(\n"
                '    "Database",\n'
                "    {\n"
                f"{inner}\n"
                "    },\n"
                ")"
            )
        else:
            blocks.append("class Database(TypedDict):\n    pass")

    return _ruff_format("\n\n".join(blocks) + "\n")


def _ruff_format(source: str) -> str:
    """Best-effort ``ruff format`` pass; returns ``source`` unchanged if ruff
    is unavailable (it is a dev dependency, not a runtime one)."""
    try:
        result = subprocess.run(
            [sys.executable, "-m", "ruff", "format", "-"],
            input=source,
            capture_output=True,
            text=True,
            check=True,
        )
    except (OSError, subprocess.CalledProcessError):
        return source
    return result.stdout or source


def _uses_datetime(tables: list[_Table]) -> bool:
    return any("datetime" in f.py_type for t in tables for f in t.fields)
